### ISSUE TITLE
Binding to hostname throws error

### ISSUE THREAD

**Issue by jeremymcgee73** [Badgerati/Pode#217]
I'm having an issue when I try to bind a cert to a specific hostname. If I use the wildcard, I can bind to the port using the cert. I have included the error below. I may also add a feature request to choose a cert based on thumbprint. Thank you!

```powershell
#Doesn't work
listen 'server.testing.net:8443' https -cert 'server.testing.net'
#Works
listen '*:8443' https -cert 'server.testing.net'
```

```
Binding server.testing.net to server.testing.net... Done
Failed to attach certificate:
The parameter is incorrect.
At C:\Program Files\WindowsPowerShell\Modules\Pode\0.27.2\Tools\Server.ps1:193 char:9
+         throw $_.Exception
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by Badgerati** [comment]
Ah, I think I can see why that might be happening: it's trying to bind the certificate to a `host:port` rather than an `ip:port` so `netsh` is throwing a wobbly! What I think I'll do is have it so that by default, for hostnames, it binds the cert to `0.0.0.0:port` - unless a new parameter, say `HostIP` is supplied.

Also, I like the idea of getting a cert based on thumbprint!

**Comment by jeremymcgee73** [comment]
Thank you! I would rather bind to the hostname that the wildcard. There are security reasons for this. Here is a PR I submitted to add hostname support to Polaris that may help. https://github.com/PowerShell/Polaris/commit/a0117afb7308273d869167af2b3d8be4f5ed8fe4

Here is the warning about binding to a wildcard. Thank you!
https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener?view=netframework-4.7.2

**Comment by Badgerati** [comment]
Thanks for the PR and link, might put that warning into the Pode docs as well!

I haven't had chance to test it, but what I just pushed into the commit above should allow you to bind certs against hostnames (branched from v0.27.2). I dug a bit deeper, and turns out that `netsh` also has a `hostnameport` tag now rather than just `ipport` 😄

**Comment by Badgerati** [comment]
Just managed to test it, and was able to successfully bind a cert to a `hostname:port` and browse the website 😄 no extra changes to the `listen` function, so just works as normal.

Unless there's anything else you'd like, I'll try and get this out as a v0.27.3.

**Comment by jeremymcgee73** [comment]
I pulled the latest version for github and I am still getting the same error. I did `netsh http show sslcert` on the server and there is no sslcert added for the host name. Let me know if you need anything else! This is on Server 2016 and PowerShell 5.1.

**Comment by Badgerati** [comment]
@jeremymcgee73 Which branch did you use, `develop` or `Issue-217`? I was testing with `Issue-217` on Win10+PS5.1

**Comment by jeremymcgee73** [comment]
Ohhhh. I was testing with master :-)

**Comment by jeremymcgee73** [comment]
I was testing with develop. I'll try with Issue-217!

**Comment by jeremymcgee73** [comment]
Thanks! It does work!
