### ISSUE TITLE
Why can't I use alternate port for Views?

### ISSUE THREAD

**Issue by sijet-dot** [Badgerati/Pode#663]
### Question
I'm sorry if this is the wrong place to ask this or if this has already been answered, I couldn't find anything when searching...

I'm trying to build a secondary Pode server to create a different API on the same machine, so I am changing my endpoints' ports, but I cannot imagine why the Views keep returning 404 pages when I'm using port 591 for my pages endpoint. The view loads just fine if I change the port back to 80 (but that will of course conflict with my main server listening on 80).

I feel like I must be missing something but I can't see anything in the documentation that would indicate what I am missing. How can I get this to work so the page renders properly using port 591 for all views.

I am using Pode 2.0.3.

### .\server.ps1
``` PowerShell
Import-Module -Name Pode -MaximumVersion 2.99.99 -Force

Start-PodeServer -FilePath .\server-debugscriptblock.ps1 -Threads 2
```

### .\server-debugscriptblock.ps1
``` PowerShell
{
    Add-PodeEndpoint -Address localhost -Port 8008 -Protocol Http -Name 'routes-endpoint'

    Add-PodeEndpoint -Address localhost -Hostname 'localhost' -Port 591 -Protocol Http -Name 'pages-endpoint'

    Set-PodeViewEngine -Type Pode

    Add-PodeRoute -EndpointName 'routes-endpoint' -Method POST `
        -Path '/api/tool' `
        -FilePath '.\routes\tool.ps1'

    # render the index.pode in the /views directory
    Add-PodeRoute -Method GET -Path '/' -EndpointName 'pages-endpoint' -ScriptBlock {
        Write-PodeViewResponse -Path 'index'
    }
}
```

### .\views\index.pode
``` Html
<!-- /views/index.pode -->
<!DOCTYPE pode>
<html>
    <head>
        <title>Title</title>
    </head>
    <body>
        <span>$([DateTime]::Now.ToString('yyyy-MM-dd HH:mm:ss');)</span>

    </body>
</html>
```

### Navigating to localhost:591
I get a 404 error page:
![image](https://user-images.githubusercontent.com/60121431/104940884-56b01b80-5980-11eb-9315-9f5096fe686c.png)

**Comment by Badgerati** [comment]
Hey @sijet-dot,

It would seem there's a bug when the `-Hostname` parameter is set to `localhost` on `Add-PodeEndpoint`, and using `-EndpointName` on a route for that endpoint. If you you remove the `-Hostname` it should work:

```powershell
Add-PodeEndpoint -Address localhost -Port 591 -Protocol Http -Name 'pages-endpoint'
```

I'll get this fixed so `-Hostname 'localhost'` works!

**Comment by sijet-dot** [comment]
I tested my server using port 591 with localhost and it worked, but it is not working on my server machine when I switch the `Add-PodeEndpoint` calls to use the actual machine name:

``` PowerShell
Add-PodeEndpoint -Address 10.1.22.39 -Hostname 'qa-dockertools.contoso.local' -Port 8008 -Protocol Http -Name 'routes-endpoint'

Add-PodeEndpoint -Address 10.1.22.39 -Hostname 'qa-dockertools.contoso.local' -Port 591 -Protocol Http -Name 'pages-endpoint'
````

When running this on my server, I can hit the server on port 591 and with that hostname, but I get a 404 error page.

**Comment by Badgerati** [comment]
Localhost and ComputerName suffered from the same bug; are you able to try using the code changes in the commit above? They should resolve the issue for you.

**Comment by sijet-dot** [comment]
I should have been more clear, I was able to test commit 89e428c on my local machine and on my server, I am still getting 404 errors using this commit from my server, but not from my local machine when using localhost. I copied the built pode directory up to my server and uninstalled Pode 2.0.3 to ensure I used this commit and tried.

**Comment by Badgerati** [comment]
Hi @sijet-dot,

Are you all right to double check on your server? I have edited the commit a little bit, but the former also worked for me as well.

I tried myself on a server with 2 endpoints setup like yours above: with the server's IP and Name, ports 8008/591 and HTTP, and using -Name/-EndpointName. For me it worked locally on the server, and externally as well 🤔 

So for me:

```powershell
Add-PodeEndpoint -Address 10.4.0.6 -Hostname 'qa-dockertools.contoso.local' -Port 8008 -Protocol Http -Name 'routes-endpoint'
Add-PodeEndpoint -Address 10.4.0.6 -Hostname 'qa-dockertools.contoso.local' -Port 591 -Protocol Http -Name 'pages-endpoint'

Add-PodeRoute -Method GET -Path '/' -EndpointName 'pages-endpoint' -ScriptBlock {
    Write-PodeViewResponse -Path 'index'
}
```

and `http://qa-dockertools.contoso.local:591/` works - on the box and off the box.

**Comment by sijet-dot** [comment]
@Badgerati I must have messed up testing on the box, because yes, it's working now using that same commit! Thanks!

**Comment by Badgerati** [comment]
I'll get this merge then, the same changes are also in Issue-669 with further improvements for more use cases - which should also be getting merged soon.
